# -*- coding: utf-8 -*-
"""Elephant_HW2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tAy_Kzx0znhLWgX6tYt5jkOdvscADxlb

# ElephantGrow – Smart Basil Monitoring System

This project combines:
- Inverted Index Search Engine
- RAG (Retrieval Augmented Generation)
- Gemini Vision AI
- Firebase Realtime Database
- Gradio User Interface

The system allows users to:
1. Search academic papers about basil diseases
2. Analyze basil leaf images using AI
3. Simulate IoT sensor readings
4. Store data in Firebase

## Imports + Setup
"""

# ==========================================
# 1. IMPORTS
# ==========================================
import gradio as gr
import pandas as pd
import random
import re
import json
import hashlib
import requests
from datetime import datetime
from collections import defaultdict
from PIL import Image

import nltk
from nltk.stem import WordNetLemmatizer

import firebase_admin
from firebase_admin import credentials, db
import google.auth.credentials

from google import genai
from google.colab import userdata

# ==========================================
# 2. NLTK SETUP (MUST RUN BEFORE ARTICLES)
# ==========================================
try:
    nltk.download('wordnet', quiet=True)
    nltk.download('omw-1.4', quiet=True)
    nltk.download('punkt', quiet=True)
    lemmatizer = WordNetLemmatizer()
    print("✅ NLTK & Lemmatizer ready.")
except Exception as e:
    print(f"⚠️ NLTK error: {e}")
    class DummyLemmatizer:
        def lemmatize(self, word): return word
    lemmatizer = DummyLemmatizer()

# ==========================================
# 3. GEMINI API SETUP
# ==========================================
try:

    gemini_api_key = userdata.get("GEMINI_API_KEY")
except Exception:

    gemini_api_key = "******************************"
    print("⚠️ Secret GEMINI_API_KEY not found. Using fallback key.")

client = genai.Client(api_key=gemini_api_key)

class UnauthenticatedCreds(google.auth.credentials.AnonymousCredentials):
    def refresh(self, request): pass
    @property
    def valid(self): return True

firebase_json = None
try:
    firebase_json = userdata.get("FIREBASE_SERVICE_ACCOUNT_JSON")
except Exception:
    pass

if not firebase_admin._apps:
    try:
        if firebase_json:

            cred = credentials.Certificate(json.loads(firebase_json))
            firebase_admin.initialize_app(cred, {
                "databaseURL": "https://elephantgrow-2026-default-rtdb.firebaseio.com/"
            })
            print("✅ Connected to Firebase as Admin.")
        else:

            firebase_admin.initialize_app(UnauthenticatedCreds(), {
                "databaseURL": "https://elephantgrow-2026-default-rtdb.firebaseio.com/"
            })
            print("✅ Connected to Firebase in Public Mode (No Secret Needed).")
    except Exception as e:
        print(f"❌ Firebase initialization failed: {e}")
else:
    print("ℹ️ Firebase already initialized.")

print("🚀 Setup Complete!")

"""### index words"""

INDEX_WORDS = set(db.reference("index_words").get())

"""## Inverted Index and RAG Search Engine"""

# ==========================================
# SEARCH ENGINE WITH RAG
# ==========================================

STOP_WORDS = {
    "the", "is", "at", "which", "on", "and", "a", "an", "to", "in", "of", "for",
    "with", "it", "that", "by", "from", "this", "are", "was", "were", "be", "as",
    "or", "but", "not", "can", "has", "have", "had"
}

class BasilSearchEngine:
    def __init__(self):
        self.inverted_index = defaultdict(list)
        self.titles = []
        self.urls = []

    def build_index(self, titles, contents, urls):
        """Build inverted index using only the 20 selected index words."""

        self.titles = titles
        self.doc_content = dict(enumerate(contents))
        self.urls = urls
        self.inverted_index.clear()

        for doc_id, text in enumerate(contents):
            clean_text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text.lower())

            words = [
                lemmatizer.lemmatize(w)
                for w in clean_text.split()
            ]

            seen = set()

            for word in words:
                if word in INDEX_WORDS and word not in seen:
                    self.inverted_index[word].append(doc_id)
                    seen.add(word)

        # Make sure all 20 index words exist in the index,
        # even if some words do not appear in the article summaries.
        for word in INDEX_WORDS:
            self.inverted_index[word]

        return (
            f"Index built with {len(self.inverted_index)} index words "
            f"from {len(titles)} articles."
        )

    def process_query(self, query):
        """Clean and lemmatize user query."""

        clean_query = re.sub(r'[^a-zA-Z0-9\s]', ' ', query.lower())

        query_words = [
            lemmatizer.lemmatize(w)
            for w in clean_query.split()
            if w not in STOP_WORDS and len(w) > 2
        ]

        return query_words

    def search(self, query):
        """RAG Implementation: Retrieval + simulated augmented generation."""

        if not query or not query.strip():
            return "Please enter a search term."

        query_words = self.process_query(query)

        use_or = " OR " in query.upper()

        results = set()
        scores = defaultdict(int)

        # === RETRIEVAL PHASE ===
        for word in query_words:

            if word in self.inverted_index:
                docs = set(self.inverted_index[word])

                # Ignore index words that exist but have no documents
                if not docs:
                    continue

                if not results:
                    results = docs
                else:
                    if use_or:
                        results = results.union(docs)
                    else:
                        results = results.intersection(docs)

                # Ranking score
                for doc_id in docs:
                    content = self.doc_content[doc_id].lower()
                    title = self.titles[doc_id].lower()

                    scores[doc_id] += content.count(word)
                    scores[doc_id] += title.count(word) * 2

        if not results:
            return "No relevant academic documents found."

        # === AUGMENTED GENERATION PHASE ===
        output = f"RAG Results for: **{query}**\n\n"

        ranked_results = sorted(
            results,
            key=lambda doc_id: scores[doc_id],
            reverse=True
        )

        for doc_id in ranked_results:
            title = self.titles[doc_id]
            url = self.urls[doc_id]
            snippet = self.doc_content.get(doc_id, "")[:480] + "..."

            output += f"**{title}**\n"
            output += f"{url}\n"
            output += f"**Relevant Excerpt:** {snippet}\n\n"

            # Simulated AI generation
            output += (
                f"**🧠 AI Insight:** This paper is relevant to **{query}** "
                "because it discusses basil disease, resistance, environmental "
                "conditions, or growth management. "
            )

            output += (
                "The retrieved research suggests that environmental control, "
                "resistant varieties, and proper management practices can help "
                "reduce disease pressure and improve basil health.\n\n"
            )

            output += "-" * 70 + "\n\n"

        return output

    def retrieve_context(self, query, top_k=3):
        """Retrieve the most relevant articles as context for Gemini."""

        if not query or not query.strip():
            return "No query provided."

        query_words = self.process_query(query)

        scores = defaultdict(int)

        for word in query_words:
            if word in self.inverted_index:
                docs = self.inverted_index[word]

                for doc_id in docs:
                    content = self.doc_content[doc_id].lower()
                    title = self.titles[doc_id].lower()

                    scores[doc_id] += content.count(word)
                    scores[doc_id] += title.count(word) * 2

        if not scores:
            return "No relevant academic context found."

        ranked_docs = sorted(
            scores.keys(),
            key=lambda doc_id: scores[doc_id],
            reverse=True
        )[:top_k]

        context = ""

        for doc_id in ranked_docs:
            context += f"Title: {self.titles[doc_id]}\n"
            context += f"Summary: {self.doc_content[doc_id]}\n"
            context += f"URL: {self.urls[doc_id]}\n\n"

        return context

"""## Academic Knowledge Base"""

# === 5 Academic Articles ===
titles = [
    "Effects of Agronomic Practices on the Severity of Sweet Basil Downy Mildew",
    "Predicting the Resistance of Basil Entries to Downy Mildew",
    "Effective Downy Mildew Management in Basil Using Resistant Varieties",
    "Susceptibility of Basil Cultivars and Breeding Lines to Downy Mildew",
    "Interactive Impacts of Temperature and Elevated CO2 on Basil Growth"
]

contents = [
    """
    Sweet basil is highly susceptible to downy mildew disease caused by Peronospora belbahrii.
    This study examined the effects of agronomic practices on disease severity under greenhouse
    and walk-in tunnel conditions. The researchers investigated irrigation methods, plant density,
    greenhouse air circulation, tunnel orientation, polyethylene mulch, humidity, and temperature
    effects on basil growth and disease susceptibility. Increased air circulation, reduced humidity,
    improved ventilation, and lower planting density significantly reduced mildew severity.
    The study also showed that environmental management and proper cultivation practices can
    improve basil resistance and reduce disease pressure in commercial basil production systems.
    """,
    """
    Forty-five basil accessions, cultivars, and breeding lines were evaluated for resistance
    to basil downy mildew disease. The study focused on identifying resistant basil varieties
    with lower disease severity and reduced susceptibility under controlled environmental conditions.
    Researchers compared resistant and susceptible basil entries and analyzed their potential use
    in future breeding programs. Several cultivars demonstrated strong resistance to mildew infection,
    making them valuable candidates for sustainable basil disease management and greenhouse production.
    """,
    """
    This research evaluated effective management strategies for basil downy mildew disease in
    commercial basil production. The study examined the integration of resistant basil varieties,
    fungicide applications, and environmental management practices to reduce disease severity
    and improve basil growth. Results showed that combining resistant cultivars with timely fungicide
    treatments provided the best mildew control under greenhouse and field conditions. Proper humidity
    management and preventive disease monitoring also reduced susceptibility and improved basil health.
    """,
    """
    Significant variation in susceptibility to downy mildew disease was observed among commercial
    basil cultivars and breeding lines grown under greenhouse conditions. The study compared sweet basil
    variities for resistance, disease severity, and susceptibility to Peronospora belbahrii infection.
    Several cultivars demonstrated partial resistance, while others were highly susceptible to mildew
    development under high humidity and temperature conditions. The findings support future basil breeding
    efforts focused on resistant varieties and improved disease management strategies.
    """,
    """
    This study investigated the interactive effects of elevated CO2 concentration and temperature
    on basil growth, physiology, and disease susceptibility. Researchers evaluated how environmental
    stress conditions influence basil development, greenhouse productivity, and resistance to disease.
    Elevated CO2 levels significantly affected basil growth parameters, photosynthesis, and physiological
    responses, while increased temperature altered susceptibility to downy mildew disease. The findings
    highlight the importance of environmental control, greenhouse climate management, and adaptation
    strategies for sustainable basil cultivation under changing climate conditions.
    """
]

urls = [
    "https://doi.org/10.3390/plants10050907",
    "https://doi.org/10.1007/s00425-025-04703-3",
    "https://doi.org/10.1094/PHP-02-21-0041-FI",
    "https://doi.org/10.21273/HORTSCI.45.9.1416",
    "https://doi.org/10.3390/horticulturae7050112"
]

academic_context = ""
for title, content, url in zip(titles, contents, urls):
    academic_context += f"Title: {title}\n"
    academic_context += f"Summary: {content}\n"
    academic_context += f"URL: {url}\n\n"

engine = BasilSearchEngine()
print(engine.build_index(titles, contents, urls))

print(f"{'Term':<20} | {'DocIDs'}")
print("-" * 40)
for word, doc_ids in sorted(engine.inverted_index.items()):
    if doc_ids:
        print(f"{word:<20} | {doc_ids}")

"""## IoT Sensor Simulation"""

def save_sensor_data(temp, humidity, soil):
    try:
        ref = db.reference("sensor_readings")

        new_entry = ref.push({"temperature": temp,"humidity": humidity,"soil_moisture": soil,"timestamp": datetime.now().isoformat()})

        return f"Real sensor data saved to Firebase! ID: {new_entry.key}"

    except Exception as e:
        return f" Data loaded, but Firebase save failed: {e}"

def fetch_latest_feed(feed_name):
    BASE_URL = "https://server-cloud-v645.onrender.com/"
    response = requests.get(
        f"{BASE_URL}/history",
        params={"feed": feed_name,"limit": 1})

    data = response.json()
    print("URL:", response.url)
    print("STATUS:", response.status_code)
    print("JSON:", response.json())
    if "data" not in data or len(data["data"]) == 0:
        raise ValueError(f"No data found for {feed_name}")

    value = data["data"][0]["value"]

    return float(str(value).strip())
def update_iot_dashboard():
    try:
        temp = fetch_latest_feed("temperature")
        humidity = fetch_latest_feed("humidity")
        soil = fetch_latest_feed("soil")

        save_status = save_sensor_data(temp, humidity, soil)

        return (str(temp), str(humidity), str(soil), save_status)
    except Exception as e:
        return (None, None, None, f" {str(e)}")


def get_history_for_plot():
    try:
        readings = db.reference("sensor_readings").get()

        if not readings:
            return pd.DataFrame({
                "Reading": [],
                "Temperature (°C)": []
            })

        rows = []

        for key, value in readings.items():
            rows.append({
                "Time": value.get("timestamp", ""),
                "Temperature (°C)": value.get("temperature", "")
            })

        df = pd.DataFrame(rows)

        df["Time"] = pd.to_datetime(
            df["Time"],
            errors="coerce"
        )

        df["Temperature (°C)"] = pd.to_numeric(
            df["Temperature (°C)"],
            errors="coerce"
        )

        df = df.dropna(
            subset=["Time", "Temperature (°C)"]
        )

        df = df.sort_values("Time").tail(10)

        df = df.reset_index(drop=True)

        df = df.reset_index(drop=True)

        df["Reading"] = [str(i)for i in range(1, len(df) + 1)]

        return df[["Reading", "Temperature (°C)"]]

    except Exception as e:
        print("Firebase graph error:", e)

        return pd.DataFrame({
            "Reading": [],
            "Temperature (°C)": []
        })

"""## Gemini Vision Disease Analysis"""

def real_ai_analysis(img_path):
    if not img_path:
        return "⚠️ Please upload a leaf photo first."

    try:
        raw_img = Image.open(img_path)
        rgb_img = raw_img.convert("RGB")

        # STEP 1: Ask Gemini to extract search keywords from the image
        keyword_prompt = """
        Look at this basil leaf image.

        Extract 3 to 6 short search keywords that describe the visible symptoms or possible causes.

        Examples:
        downy mildew
        yellowing
        humidity
        fungal disease
        leaf spots
        temperature stress

        Return only the keywords, separated by spaces.
        """

        keyword_response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[keyword_prompt, rgb_img]
        )

        if keyword_response and keyword_response.text:
            search_query = keyword_response.text.strip()
        else:
            search_query = "basil disease downy mildew yellowing humidity"

        # STEP 2: Retrieve relevant academic articles
        retrieved_context = engine.retrieve_context(search_query, top_k=3)

        # STEP 3: Final Gemini analysis using the retrieved articles
        final_prompt = f"""
        You are a professional plant pathologist.

        Analyze this basil leaf image using the academic context below.

        Retrieved academic context:
        {retrieved_context}

        Your tasks:
        1. Describe the visible symptoms.
        2. Give the most likely diagnosis.
        3. Explain which academic article supports your diagnosis.
        4. Include the relevant article link.
        5. Give practical recommendations for the grower.
        6. Mention if the image is unclear or if diagnosis is uncertain.

        Write your answer in clear English.
        """

        final_response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[final_prompt, rgb_img]
        )

        if final_response and final_response.text:
            return final_response.text
        else:
            return "❌ Gemini returned an empty response. Try a clearer photo."

    except Exception as e:
        error_text = str(e)

        if "429" in error_text or "quota" in error_text.lower():
            return (
                "⚠️ Gemini quota/rate limit reached.\n\n"
                "Please wait and try again, or check your Gemini API rate limits."
            )

        return f"❌ Error: {error_text}"

"""### Race comp"""

# ==========================================
# RACE / USER POINTS SYSTEM
# ==========================================

def normalize_email(email):
    return (email or "").strip().lower()


def normalize_name(name):
    return (name or "").strip()


def is_valid_email(email):
    email = normalize_email(email)
    return re.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$", email) is not None


def email_to_user_key(email):
    email = normalize_email(email)
    return hashlib.sha256(email.encode()).hexdigest()


def add_points_to_user(name, email, action_name, points=100):
    name = normalize_name(name)
    email = normalize_email(email)

    if not name:
        return "⚠️ Name was not entered, so no points were added."

    if not is_valid_email(email):
        return "⚠️ Email was invalid, so no points were added."

    user_key = email_to_user_key(email)
    user_ref = db.reference("race_users").child(user_key)

    user_data = user_ref.get()

    if user_data is None:
        current_points = 0
    else:
        current_points = int(user_data.get("points", 0))

    new_points = current_points + points

    user_ref.update({
        "name": name,
        "email": email,
        "points": new_points,
        "last_action": action_name,
        "updated_at": datetime.now().isoformat()
    })

    db.reference("race_events").push({
        "name": name,
        "email": email,
        "action": action_name,
        "points_added": points,
        "timestamp": datetime.now().isoformat()
    })

    return f"🏆 {name} earned +{points} points for {action_name}!"

def mask_email(email):
    email = normalize_email(email)

    if "@" not in email:
        return ""

    name, domain = email.split("@", 1)

    if len(name) <= 2:
        masked_name = name[0] + "*"
    else:
        masked_name = name[:2] + "***"

    return masked_name + "@" + domain

def get_leaderboard():
    users = db.reference("race_users").get()

    if not users:
        return pd.DataFrame({
            "Rank": [],
            "Name": [],
            "Email": [],
            "Points": [],
            "Last Action": []
        })

    rows = []

    for user_key, data in users.items():
        rows.append({
            "Name": data.get("name", "Unknown"),
            "Email": mask_email(data.get("email", "")),
            "Points": int(data.get("points", 0)),
            "Last Action": data.get("last_action", "")
        })

    rows = sorted(rows, key=lambda x: x["Points"], reverse=True)

    for i, row in enumerate(rows, start=1):
        row["Rank"] = f"#{i}"

    return pd.DataFrame(rows, columns=["Rank", "Name", "Email", "Points", "Last Action"])

"""### Wrapper and helper functions for the race"""

def show_points_popup():
    return gr.update(visible=True)


def hide_points_popup():
    return gr.update(visible=False)


def analyze_with_points(name, email, img_path):
    result = real_ai_analysis(img_path)

    if result.startswith("⚠️") or result.startswith("❌"):
        return result, get_leaderboard()

    reward_message = add_points_to_user(
        name=name,
        email=email,
        action_name="AI plant analysis",
        points=100
    )

    return result + "\n\n---\n" + reward_message, get_leaderboard()


def analyze_without_points(img_path):
    result = real_ai_analysis(img_path)
    return result + "\n\n---\nPoints were skipped.", get_leaderboard()


def search_with_points(name, email, query):
    result = engine.search(query)

    if result.startswith("Please enter") or result.startswith("No relevant"):
        return result, get_leaderboard()

    reward_message = add_points_to_user(
        name=name,
        email=email,
        action_name="Knowledge Base search",
        points=100
    )

    return result + "\n\n---\n" + reward_message, get_leaderboard()


def search_without_points(query):
    result = engine.search(query)
    return result + "\n\n---\nPoints were skipped.", get_leaderboard()
# ==========================================
# DAILY MISSION - עם בדיקת "פעם אחת ביום"
# ==========================================

def has_claimed_today(email):
    """בודק אם המשתמש כבר לקח נקודות היום"""
    if not email:
        return False
    user_key = email_to_user_key(email)
    user_data = db.reference(f"race_users/{user_key}").get()

    if not user_data or "last_daily_claim" not in user_data:
        return False

    last_claim = user_data["last_daily_claim"]
    today = datetime.now().date().isoformat()
    return last_claim == today


def daily_task_with_points(name, email):
    name = normalize_name(name)
    email = normalize_email(email)

    if not name or not is_valid_email(email):
        return "⚠️ Please enter valid name and email", get_leaderboard(), gr.update(visible=True)

    if has_claimed_today(email):
        return (
            "⚠️ You have already claimed your daily bonus today!\n"
            "Come back tomorrow for another 50 points 🌱",
            get_leaderboard(),
            gr.update(visible=True)
        )

    reward_message = add_points_to_user(
        name=name,
        email=email,
        action_name="Daily Basil Check",
        points=50
    )


    user_key = email_to_user_key(email)
    db.reference(f"race_users/{user_key}").update({
        "last_daily_claim": datetime.now().date().isoformat()
    })

    return reward_message, get_leaderboard(), gr.update(visible=True)


def daily_task_without_points():
    return "Points skipped for today.", get_leaderboard(), gr.update(visible=True)

"""### Desgin edits

"""

LOADING_HTML = """
<div class="loading-box">
    <div class="loader-circle"></div>
    <div class="loading-text">Analyzing plant,<br>please wait...</div>
</div>
"""

CUSTOM_CSS = """
.loading-box {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 25px;
    margin-top: 15px;
    border-radius: 16px;
    background: #f0fdf4;
    border: 2px solid #86efac;
    text-align: center;
}

.loader-circle {
    width: 70px;
    height: 70px;
    border: 8px solid #dcfce7;
    border-top: 8px solid #16a34a;
    border-radius: 50%;
    animation: spin 1s linear infinite;
    margin-bottom: 15px;
}

.loading-text {
    font-size: 18px;
    font-weight: bold;
    color: #166534;
}

.points-popup {
    padding: 22px;
    border-radius: 18px;
    background: #ffffff;
    border: 2px solid #86efac;
    box-shadow: 0 12px 30px rgba(0,0,0,0.18);
    margin-top: 20px;
}

.points-title {
    font-size: 22px;
    font-weight: bold;
    color: #166534;
    text-align: center;
}

.points-subtitle {
    text-align: center;
    color: #365314;
    margin-bottom: 15px;
}

@keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
}
.gradio-container textarea {
    overflow-y: hidden !important;
    resize: none !important;
}
"""

"""## Gradio UI"""

# ==========================================
# GRADIO INTERFACE
# ==========================================
loading = gr.HTML(
    value=LOADING_HTML,
    visible=False
)

def show_loading():
    return gr.update(value=LOADING_HTML, visible=True), ""

def hide_loading():
    return gr.update(visible=False)

with gr.Blocks(
    theme=gr.themes.Soft(primary_hue="green", secondary_hue="emerald"),
    title="ElephantGrow",
    css=CUSTOM_CSS
) as demo:

    gr.Markdown("# 🐘 ElephantGrow\n**Smart Basil Monitoring System**")

    with gr.Tabs():

        # ==========================
        # DASHBOARD TAB
        # ==========================
        with gr.TabItem("🏠 Dashboard"):

            gr.Markdown("### 24-Hour Temperature Trend")

            temp_plot = gr.LinePlot(value=get_history_for_plot(),x="Reading",y="Temperature (°C)",height=380)

            refresh_plot_btn = gr.Button("🔄 Refresh Graph")

            refresh_plot_btn.click(fn=get_history_for_plot,inputs=[],outputs=temp_plot)



        # ==========================
        # AI ANALYSIS TAB
        # ==========================
        with gr.TabItem("📸 AI Analysis"):
            gr.Markdown("### AI Disease Detection")

            img_input = gr.Image(
                label="Upload Leaf Photo",
                type="filepath",
                height=400
            )

            analyze_btn = gr.Button(
                "🔍 Analyze Leaf",
                variant="primary",
                size="large"
            )

            with gr.Group(visible=False, elem_classes="points-popup") as ai_points_popup:
                gr.HTML("""
                <div class="points-title">Earn Race Points</div>
                <div class="points-subtitle">
                    Enter your name and email to get +100 points, or skip.
                </div>
                """)

                ai_name = gr.Textbox(label="Name", placeholder="Enter your name")
                ai_email = gr.Textbox(label="Email", placeholder="Enter your email")

                with gr.Row():
                    ai_continue_btn = gr.Button("✅ Continue and Add Points", variant="primary")
                    ai_skip_btn = gr.Button("Skip Points")

            loading = gr.HTML(
                value=LOADING_HTML,
                visible=False
            )

            result = gr.Markdown(label="AI Analysis Result")

              # ==========================
        # SENSORS TAB
        # ==========================
        with gr.TabItem("📡 Sensors"):
            gr.Markdown("### Real-Time IoT Sensors (Live from Raspberry Pi)")

            with gr.Row():
              temp = gr.Textbox(label="🌡️ Temperature (°C)", value="", interactive=False,lines=1)
              humidity = gr.Textbox(label="Humidity (%)", value="", interactive=False,lines=1)
              soil = gr.Textbox(label="Soil Moisture (%)", value="", interactive=False,lines=1)
            status = gr.Textbox(label="Status",interactive=False,lines=1)
            fetch_btn = gr.Button("Fetch Real Data & Save to Firebase",variant="primary")
            fetch_btn.click(fn=update_iot_dashboard,inputs=[],outputs=[temp, humidity, soil, status])

           # ==========================
        # KNOWLEDGE BASE TAB
        # ==========================
        with gr.TabItem("🔍 Knowledge Base"):
            gr.Markdown("### Academic Search Engine (RAG)")

            query = gr.Textbox(
                label="Search Term",
                placeholder="mildew, resistance, CO2, humidity..."
            )

            search_btn = gr.Button(
                "🔎 Search with RAG",
                variant="primary",
                size="large"
            )

            with gr.Group(visible=False, elem_classes="points-popup") as search_points_popup:
                gr.HTML("""
                <div class="points-title">Earn Race Points</div>
                <div class="points-subtitle">
                    Enter your name and email to get +100 points, or skip.
                </div>
                """)

                search_name = gr.Textbox(label="Name", placeholder="Enter your name")
                search_email = gr.Textbox(label="Email", placeholder="Enter your email")

                with gr.Row():
                    search_continue_btn = gr.Button("✅ Continue and Add Points", variant="primary")
                    search_skip_btn = gr.Button("Skip Points")

            output = gr.Markdown(label="RAG Results")
        # ==========================
        # RACE TAB
        # ==========================
        with gr.TabItem("🏆 Race"):
            gr.Markdown("### Healthy Garden Race")

            leaderboard_table = gr.Dataframe(
                value=get_leaderboard(),
                label="Leaderboard",
                interactive=False

            )
            gr.Markdown("### 🌿 Daily Mission (Once per day)")

            daily_btn = gr.Button("✅ I watered the basil today! (+50 pts)",
                                variant="primary")

            with gr.Group(visible=False, elem_classes="points-popup") as daily_points_popup:
                gr.HTML("""
                <div class='points-title'>🌟 Daily Bonus</div>
                <div class='points-subtitle'>
                    One time per day only<br>
                    Enter your details to claim 50 points
                </div>
                """)
                d_name = gr.Textbox(label="Name", placeholder="Enter your name")
                d_email = gr.Textbox(label="Email", placeholder="Enter your email")

                with gr.Row():
                   d_continue_btn = gr.Button("✅ Claim 50 Points", variant="primary")
                   d_skip_btn = gr.Button("Skip for now")


            refresh_leaderboard_btn = gr.Button("🔄 Refresh Leaderboard")

        # ==========================================
        # BUTTON EVENTS
        # ==========================================

        # AI Analysis flow
        analyze_btn.click(
            fn=show_points_popup,
            inputs=[],
            outputs=ai_points_popup
        )

        ai_continue_event = ai_continue_btn.click(
            fn=hide_points_popup,
            inputs=[],
            outputs=ai_points_popup
        ).then(
            fn=show_loading,
            inputs=[],
            outputs=[loading, result]
        )

        ai_continue_event.then(
            fn=analyze_with_points,
            inputs=[ai_name, ai_email, img_input],
            outputs=[result, leaderboard_table]
        ).then(
            fn=hide_loading,
            inputs=[],
            outputs=loading
        )

        ai_skip_event = ai_skip_btn.click(
            fn=hide_points_popup,
            inputs=[],
            outputs=ai_points_popup
        ).then(
            fn=show_loading,
            inputs=[],
            outputs=[loading, result]
        )

        ai_skip_event.then(
            fn=analyze_without_points,
            inputs=img_input,
            outputs=[result, leaderboard_table]
        ).then(
            fn=hide_loading,
            inputs=[],
            outputs=loading
        )

        # Knowledge Base flow
        search_btn.click(
            fn=show_points_popup,
            inputs=[],
            outputs=search_points_popup
        )

        search_continue_btn.click(
            fn=hide_points_popup,
            inputs=[],
            outputs=search_points_popup
        ).then(
            fn=search_with_points,
            inputs=[search_name, search_email, query],
            outputs=[output, leaderboard_table]
        )

        search_skip_btn.click(
            fn=hide_points_popup,
            inputs=[],
            outputs=search_points_popup
        ).then(
            fn=search_without_points,
            inputs=query,
            outputs=[output, leaderboard_table]
        )

        refresh_leaderboard_btn.click(
            fn=get_leaderboard,
            inputs=[],
            outputs=leaderboard_table
        )
        daily_btn.click(
            fn=show_points_popup,
            outputs=daily_points_popup
        )

        d_continue_btn.click(
           fn=hide_points_popup,
           outputs=daily_points_popup
        ).then(
           fn=daily_task_with_points,
           inputs=[d_name, d_email],
           outputs=[gr.Markdown(visible=False), leaderboard_table]
        )
        d_skip_btn.click(
          fn=hide_points_popup,
          outputs=daily_points_popup
       ).then(
          fn=daily_task_without_points,
          outputs=[output, leaderboard_table, daily_btn]
       )

"""## Launch"""

demo.queue().launch(share=True, debug=True)