# -*- coding: utf-8 -*-
"""Tirgul2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5w5hNkMEHiiiGm2XdBLBSo0at0XryKE
"""

from google.colab import drive
drive.mount('/content/drive')

import json
import ipywidgets as widgets
from IPython.display import display, clear_output

file_path ="/content/drive/MyDrive/Cloud intro course/students.json"
def load_students():
    with open(file_path, "r", encoding="utf-8") as file:
        return json.load(file)
def save_students(students):
    with open(file_path, "w", encoding="utf-8") as file:
        json.dump(students, file, ensure_ascii=False, indent=4)

students = load_students()

def find_student_by_email(email):
    for student in students:
        if student["email"] == email:
            return student
    return None


def show_student_details(email):
    student = find_student_by_email(email)

    with output:
        clear_output()

        if student is None:
            print("הסטודנט לא נמצא")
            return

        print("שם:", student["first_name"])
        print("שם משפחה:", student["last_name"])
        print("מייל:", student["email"])
        print("קורסים שנלמדו בסמסטר האחרון:")

        for course in student["courses_last_semester"]:
            print("-", course)

        print("קישור מעניין:", student["interesting_connection"])
        print("תוכנה אהובה:", student.get("favorite_program", "לא הוגדר"))

        favorite_program_input.value = student.get("favorite_program", "")

def on_student_change(change):
    selected_email = change["new"]
    show_student_details(selected_email)


def on_update_clicked(button):
    selected_email = student_dropdown.value
    student = find_student_by_email(selected_email)

    if student is not None:
        student["favorite_program"] = favorite_program_input.value
        save_students(students)

        with output:
            clear_output()
            print("העדכון נשמר בהצלחה בקובץ students.json")
            print()

        show_student_details(selected_email)

student_options = []

for student in students:
    full_name = student["first_name"] + " " + student["last_name"]
    student_options.append((full_name, student["email"]))

student_dropdown = widgets.Dropdown(
    options=student_options,
    description="סטודנט:"
)

favorite_program_input = widgets.Text(
    description="תוכנה:",
    placeholder="כתוב תוכנית אהובה"
)

update_button = widgets.Button(
    description="עדכן",
    button_style="success"
)

output = widgets.Output()

student_dropdown.observe(on_student_change, names="value")
update_button.on_click(on_update_clicked)

display(student_dropdown)
display(favorite_program_input)
display(update_button)
display(output)

# הצגה ראשונית של הסטודנט הראשון
show_student_details(student_dropdown.value)